---
abstract: 'parse and interact with a NetHack menu'
author:
  - 'Shawn M Moore, C<sartak@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::Deep: 0
  Test::Fatal: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: NetHack-Menu
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 0
resources:
  homepage: https://github.com/TAEB/NetHack-Menu/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/TAEB/NetHack-Menu.git
version: 0.07
