--- 
abstract: interact with NetHack's menus
author: Shawn M Moore, C<< <sartak at gmail.com> >>
build_requires: 
  Test::Exception: 0
  Test::MockObject: 0
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: NetHack-Menu
no_index: 
  directory: 
    - inc
    - t
requires: 
  Moose: 0
version: 0.01
